In [8]:
import os
import torch
import matplotlib.pyplot as plt
from datetime import datetime
import shutil
from PIL import Image

import numpy as np
import pyopengv

from scipy.spatial.transform import Rotation as rot

from tqdm import tqdm

# Util function for loading meshes
from pytorch3d.io import load_objs_as_meshes, save_obj, load_obj, load_ply
import pytorch3d

# Data structures and functions for rendering
from pytorch3d.structures import Meshes, Pointclouds

# add path for demo utils functions 
import sys
import os
import k3d
from PIL import Image

In [2]:
rots = np.load('/scratch2/fml35/experiments/leveraging_geometry_for_shape/exp_117_debug_scannet/models/rotations/R_T_torch.npz')

In [3]:
print(rots[0])

KeyError: '0 is not a file in the archive'

In [4]:
for key in rots:
    print(key)

R
T


In [6]:
print(rots["R"][8])

[[ 1.000000e+00 -0.000000e+00  8.742278e-08]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-8.742278e-08  0.000000e+00  1.000000e+00]]


In [7]:
wc_path = '/scratch2/fml35/experiments/leveraging_geometry_for_shape/exp_123_debug_scannet/wc_matches/scene0000_00-000500_2_001.npy'
model_path = '/scratch2/fml35/experiments/leveraging_geometry_for_shape/exp_117_debug_scannet/models/remeshed/bed/ab9e57b316f43962b738ef7a6757633a/model_normalized.obj'

In [10]:

vertices_gt_scaled,faces_gt_scaled,_ = load_obj(model_path,create_texture_atlas=False, load_textures=False)
wc_gt = np.load(wc_path)

plot = k3d.plot()
plot += k3d.mesh(vertices_gt_scaled,faces_gt_scaled[0],color=(64 + 128 * 256))
plot += k3d.points(wc_gt,color=(0 + 255 * 256),point_size=0.05)

plot.display()

Output()