In [1]:
import numpy as np
import json

In [14]:
wc = np.load('/data/cornucopia/fml35/experiments/debug_set/wc_matches/desk_0526_3_000.npy')
print(wc)

#  "world_coordinates_matches": [
#                     [
#                         -0.41270557045936584,
#                         0.11635338515043259,
#                         0.14823095500469208
#                     ],
#                     [
#                         0.419463574886322,
#                         -0.223514586687088,
#                         0.14825814962387085
#                     ],
#                     [
#                         0.4194728434085846,
#                         0.21247906982898712,
#                         0.14824804663658142
#                     ],
#                     [
#                         -0.41654765605926514,
#                         -0.21805863082408905,
#                         0.1482502818107605
#                     ],
#                     [
#                         -0.4203759431838989,
#                         0.21770726144313812,
#                         0.1482405960559845
#                     ]
#                 ],

[[-0.41270554  0.11635343  0.14823058]
 [ 0.41946393 -0.22351466  0.14825779]
 [ 0.41947317  0.21247916  0.14824766]
 [-0.4165476  -0.21805874  0.14824983]
 [-0.4203759   0.21770734  0.14824028]]


In [11]:
with open('/data/cornucopia/fml35/experiments/test_output_all_s2/nn_infos_gt_cat/bed_0883_00.json','r') as f:
    nn_infos = json.load(f)


print(nn_infos["nearest_neighbours"][0])

{'category': 'bed', 'name': 'bed_IKEA_FJELLSE_2', 'model': 'model/bed/IKEA_FJELLSE_2/model.obj', 'orientation': 25, 'azim': '202.5', 'elev': '015', 'path': 'bed/IKEA_FJELLSE_2/elev_015_azim_202.5.png', 'model_index': 15001, 'distance': 0.7423269152641296}


In [5]:
with open('/data/cornucopia/fml35/experiments/test_output_all_s2/matches/bed_0883_00_000.json','r') as f:
    matches = json.load(f)
print(matches)

{'pixels_real': [[140, 163], [147, 59], [91, 201], [112, 122], [87, 124], [161, 150], [156, 149]], 'pixels_rendered': [[168, 170], [147, 57], [135, 217], [115, 83], [94, 53], [202, 167], [181, 169]]}


In [3]:
with open('/data/cornucopia/fml35/experiments/shape_estimation/retrieval_plus_keypoints/date_2021_03_28_time_13_13_36_single_encoder_euclidean_s2/tests/epoch_10_predicted_date_2021_06_08_time_19_54_41_swin_epoch_66/date_2021_06_10_time_11_37_47_top_10_gt_z_swin_masks/pose_information.json','r') as f:
    all_pose = json.load(f)