In [3]:
from pytorch3d.io import load_obj
import os
import torch
from tqdm import tqdm


In [25]:
dir_path = '/scratch/fml35/datasets/3d_future/3D-FUTURE-model_reformatted/model'

mins = []
maxs = []

for cat in os.listdir(dir_path)[:1]:
    for id in os.listdir(dir_path + '/' + cat):
        print('')
        print(dir_path + '/' + cat + '/' + id)
        # verts,_,_ = load_obj(dir_path + '/' + cat + '/' + id + '/raw_model.obj')
        verts,_,_ = load_obj(dir_path + '/' + cat + '/' + id + '/model_normalized.obj')
        min,_ = torch.min(verts,dim=0)
        max,_ = torch.max(verts,dim=0)
        mins.append(min)
        maxs.append(max)
        print(min,max)
        verts,_,_ = load_obj(dir_path + '/' + cat + '/' + id + '/raw_model.obj')
        min,_ = torch.min(verts,dim=0)
        max,_ = torch.max(verts,dim=0)
        print(min,max)
      
    # {"xLen": 1.887, "zLen": 1.402, "yLen": 2.234}


/scratch/fml35/datasets/3d_future/3D-FUTURE-model_reformatted/model/bed/433123cb-172e-49ed-be20-24ca9159b0e4
tensor([-0.8623, -0.1133, -1.0000]) tensor([0.6356, 1.0000, 0.7732])
tensor([-9.4354e-01,  5.9935e-17, -1.1170e+00]) tensor([0.9433, 1.4023, 1.1167])

/scratch/fml35/datasets/3d_future/3D-FUTURE-model_reformatted/model/bed/27498740-3ec5-425a-aaa3-9f4703765e5f
tensor([-9.0382e-01, -9.4361e-05, -1.0000e+00]) tensor([0.9037, 0.8800, 1.0000])


KeyboardInterrupt: 

In [12]:
concatenated_min = torch.stack(mins)
global_min,_ = torch.min(concatenated_min,dim=0)
print(global_min)

concatenated_max = torch.stack(maxs)
global_max,_ = torch.max(concatenated_max,dim=0)
print(global_max)

tensor([-1.0000, -0.4043, -1.0000])
tensor([1., 1., 1.])
